'use client';

import React from 'react';
import { Button } from './ui/button';
import { Download, Printer, Calendar, CheckCircle, AlertCircle } from 'lucide-react';
import { calculateServiceDates, formatDate } from '@/lib/utils';
import jsPDF from 'jspdf';

interface ScheduleData {
  customerName: string;
  vehicleModel: string;
  registrationNumber: string;
  vehicleNumber: string;
  purchaseDate: string;
}

interface ServiceScheduleProps {
  data: ScheduleData;
  onReset: () => void;
}

export function ServiceSchedule({ data, onReset }: ServiceScheduleProps) {
  const purchaseDate = new Date(data.purchaseDate);
  const serviceDates = calculateServiceDates(purchaseDate);

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    
    pdf.setFillColor(0, 102, 204);
    pdf.rect(0, 0, pageWidth, 40, 'F');
    
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(24);
    pdf.setFont('helvetica', 'bold');
    pdf.text('TATA MOTORS', pageWidth / 2, 15, { align: 'center' });
    
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Service Schedule Report', pageWidth / 2, 28, { align: 'center' });
    
    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Customer Details', 20, 55);
    
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(11);
    let y = 65;
    
    pdf.text(`Customer Name: ${data.customerName}`, 20, y);
    y += 8;
    pdf.text(`Vehicle Model: ${data.vehicleModel}`, 20, y);
    y += 8;
    pdf.text(`Registration No: ${data.registrationNumber}`, 20, y);
    y += 8;
    pdf.text(`Vehicle Number: ${data.vehicleNumber}`, 20, y);
    y += 8;
    pdf.text(`Purchase Date: ${formatDate(purchaseDate)}`, 20, y);
    
    y += 20;
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.text('Scheduled Service Dates', 20, y);
    
    y += 10;
    pdf.setFillColor(240, 240, 240);
    pdf.rect(20, y, pageWidth - 40, 50, 'F');
    
    y += 10;
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text('1st Service (7 months)', 25, y);
    pdf.setFont('helvetica', 'normal');
    pdf.text(formatDate(serviceDates.firstService), 25, y + 6);
    
    y += 18;
    pdf.setFont('helvetica', 'bold');
    pdf.text('2nd Service (15 months)', 25, y);
    pdf.setFont('helvetica', 'normal');
    pdf.text(formatDate(serviceDates.secondService), 25, y + 6);
    
    y += 18;
    pdf.setFont('helvetica', 'bold');
    pdf.text('3rd Service (23 months)', 25, y);
    pdf.setFont('helvetica', 'normal');
    pdf.text(formatDate(serviceDates.thirdService), 25, y + 6);
    
    pdf.setFontSize(9);
    pdf.setTextColor(128, 128, 128);
    pdf.text('Generated by Tata Vehicle Service Tracker', pageWidth / 2, 280, { align: 'center' });
    pdf.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, pageWidth / 2, 285, { align: 'center' });
    
    pdf.save(`Service_Schedule_${data.registrationNumber}.pdf`);
  };

  const today = new Date();
  const getServiceStatus = (serviceDate: Date) => {
    if (serviceDate < today) return 'overdue';
    if (serviceDate.getTime() - today.getTime() < 30 * 24 * 60 * 60 * 1000) return 'upcoming';
    return 'scheduled';
  };

  const StatusBadge = ({ status }: { status: string }) => {
    const styles = {
      overdue: 'bg-red-100 text-red-700 border-red-300',
      upcoming: 'bg-yellow-100 text-yellow-700 border-yellow-300',
      scheduled: 'bg-green-100 text-green-700 border-green-300',
    };
    
    const icons = {
      overdue: <AlertCircle className="w-4 h-4" />,
      upcoming: <Calendar className="w-4 h-4" />,
      scheduled: <CheckCircle className="w-4 h-4" />,
    };
    
    const labels = {
      overdue: 'Overdue',
      upcoming: 'Due Soon',
      scheduled: 'Scheduled',
    };
    
    return (
      <span className={`inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-semibold border ${styles[status as keyof typeof styles]}`}>
        {icons[status as keyof typeof icons]}
        {labels[status as keyof typeof labels]}
      </span>
    );
  };

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-2xl shadow-xl p-8 border border-gray-200">
        <div className="flex items-center justify-between mb-6 pb-6 border-b border-gray-200">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-tata-blue rounded-xl flex items-center justify-center">
              <Calendar className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-gray-900">Service Schedule</h2>
              <p className="text-sm text-gray-600">Generated on {formatDate(new Date())}</p>
            </div>
          </div>
        </div>

        <div className="grid md:grid-cols-2 gap-6 mb-8">
          <div className="space-y-3">
            <div>
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Customer Name</p>
              <p className="text-lg font-semibold text-gray-900">{data.customerName}</p>
            </div>
            <div>
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Vehicle Model</p>
              <p className="text-lg font-semibold text-gray-900">{data.vehicleModel}</p>
            </div>
            <div>
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Registration Number</p>
              <p className="text-lg font-semibold text-gray-900">{data.registrationNumber}</p>
            </div>
          </div>
          <div className="space-y-3">
            <div>
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Vehicle Number</p>
              <p className="text-lg font-semibold text-gray-900">{data.vehicleNumber}</p>
            </div>
            <div>
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Purchase Date</p>
              <p className="text-lg font-semibold text-gray-900">{formatDate(purchaseDate)}</p>
            </div>
          </div>
        </div>

        <div className="space-y-4">
          <h3 className="text-xl font-bold text-gray-900 mb-4">Scheduled Service Dates</h3>
          
          <div className="bg-gradient-to-r from-blue-50 to-blue-100 border-l-4 border-tata-blue rounded-lg p-6">
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-lg font-bold text-gray-900">1st Service</h4>
              <StatusBadge status={getServiceStatus(serviceDates.firstService)} />
            </div>
            <p className="text-sm text-gray-600 mb-1">After 7 months from purchase</p>
            <p className="text-2xl font-bold text-tata-blue">{formatDate(serviceDates.firstService)}</p>
          </div>

          <div className="bg-gradient-to-r from-indigo-50 to-indigo-100 border-l-4 border-indigo-600 rounded-lg p-6">
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-lg font-bold text-gray-900">2nd Service</h4>
              <StatusBadge status={getServiceStatus(serviceDates.secondService)} />
            </div>
            <p className="text-sm text-gray-600 mb-1">After 15 months from purchase</p>
            <p className="text-2xl font-bold text-indigo-600">{formatDate(serviceDates.secondService)}</p>
          </div>

          <div className="bg-gradient-to-r from-purple-50 to-purple-100 border-l-4 border-purple-600 rounded-lg p-6">
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-lg font-bold text-gray-900">3rd Service</h4>
              <StatusBadge status={getServiceStatus(serviceDates.thirdService)} />
            </div>
            <p className="text-sm text-gray-600 mb-1">After 23 months from purchase</p>
            <p className="text-2xl font-bold text-purple-600">{formatDate(serviceDates.thirdService)}</p>
          </div>
        </div>
      </div>

      <div className="flex flex-wrap gap-4 no-print">
        <Button onClick={handlePrint} variant="outline" className="flex items-center gap-2">
          <Printer className="w-5 h-5" />
          Print Schedule
        </Button>
        <Button onClick={handleDownloadPDF} className="flex items-center gap-2">
          <Download className="w-5 h-5" />
          Download PDF
        </Button>
        <Button onClick={onReset} variant="secondary" className="ml-auto">
          Create New Schedule
        </Button>
      </div>
    </div>
  );
}
